version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:          # une seule pull request par mois pour toutes les actions
      actions:
        patterns: ["*"]
